#!/usr/bin/env bash
#
# Osync — Quick Install
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/KORThomasJeong/Osync-p/main/install.sh | bash
#
# Optional environment overrides:
#   ADMIN_EMAIL=me@example.com PUBLIC_URL=https://osync.example.com \
#     bash -c "$(curl -fsSL https://raw.githubusercontent.com/KORThomasJeong/Osync-p/main/install.sh)"
#
# What it does:
#   1. Verifies curl / openssl / docker / docker compose are installed
#   2. Downloads docker-compose.yml to the current directory
#   3. If .env doesn't exist: generates random secrets and writes a new .env
#   4. Runs `docker compose up -d` and waits for the API to become healthy
#
# Re-runs are safe: an existing .env is never overwritten.

set -euo pipefail

REPO_BASE="https://raw.githubusercontent.com/KORThomasJeong/Osync-p/main"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@localhost}"
PUBLIC_URL="${PUBLIC_URL:-http://localhost:3000}"

c_red=$'\033[31m'; c_cyan=$'\033[36m'; c_green=$'\033[32m'; c_reset=$'\033[0m'
info()  { printf "%s==>%s %s\n" "$c_cyan"  "$c_reset" "$*"; }
ok()    { printf "%sok%s  %s\n"  "$c_green" "$c_reset" "$*"; }
fail()  { printf "%serror:%s %s\n" "$c_red" "$c_reset" "$*" >&2; exit 1; }

# --- preflight -------------------------------------------------------------
for cmd in curl openssl docker; do
  command -v "$cmd" >/dev/null 2>&1 || fail "$cmd is required but not installed"
done
docker compose version >/dev/null 2>&1 \
  || fail "docker compose v2 not found (install the docker-compose-plugin)"

# --- fetch compose file ----------------------------------------------------
info "Downloading docker-compose.yml"
curl -fsSL -o docker-compose.yml "$REPO_BASE/docker-compose.yml"

# --- create .env if missing ------------------------------------------------
if [[ -f .env ]]; then
  ok ".env already exists — leaving it untouched"
else
  info "Generating .env with random secrets"

  POSTGRES_PASS="$(openssl rand -base64 24 | tr -d '=+/')"
  S3_ACCESS_KEY="$(openssl rand -hex 16)"
  S3_SECRET_KEY="$(openssl rand -base64 24 | tr -d '=+/')"
  MINIO_KMS="osync-key:$(openssl rand -base64 32)"
  BETTER_AUTH_SECRET="$(openssl rand -hex 32)"
  SYNC_TOKEN_SECRET="$(openssl rand -hex 32)"
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '=+/')"

  cat > .env <<ENV
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file private — chmod 600.

# ── PostgreSQL ─────────────────────────────────────────────
POSTGRES_USER=osync
POSTGRES_PASSWORD=${POSTGRES_PASS}
POSTGRES_DB=osync

# ── MinIO (S3-compatible storage) ─────────────────────────
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=osync-bucket
S3_REGION=us-east-1
MINIO_KMS_SECRET_KEY=${MINIO_KMS}

# ── Auth ───────────────────────────────────────────────────
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
SYNC_TOKEN_SECRET=${SYNC_TOKEN_SECRET}

# ── App ────────────────────────────────────────────────────
PORT=3000
PUBLIC_URL=${PUBLIC_URL}
CORS_ORIGIN=${PUBLIC_URL}
SELF_HOSTED=true
SYNC_TOKEN_TTL_SECONDS=120
COORDINATOR_DATA_DIR=/data/coordinators

# ── Admin account (first run only) ─────────────────────────
# After your first successful login, remove these two lines.
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ENV
  chmod 600 .env

  cat <<MSG

  ${c_green}Admin credentials${c_reset} (save the password — it is shown only once):

    Email:    ${ADMIN_EMAIL}
    Password: ${ADMIN_PASSWORD}
    URL:      ${PUBLIC_URL}

MSG
fi

# --- start stack -----------------------------------------------------------
info "Starting Docker Compose stack"
docker compose up -d

info "Waiting for API to become healthy"
for i in $(seq 1 30); do
  if curl -fsS http://localhost:3000/health >/dev/null 2>&1; then
    ok "API is healthy"
    break
  fi
  sleep 2
  [[ $i -eq 30 ]] && fail "API did not become healthy within 60s (run 'docker compose logs api')"
done

info "Open ${PUBLIC_URL%/}/admin/ in your browser to sign in"
